import { Hero } from './domain/hero';

export const HEROES: Hero[] = [
        {
            "ID": 1,
            "Name": "Alyssa K'Tal",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 5,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 2,
            "Name": "Ylenic It'kla",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 3,
            "Name": "Fondon Raas",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 4,
            "Name": "Janath Meelin",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 4,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 5,
            "Name": "Tobias Kel'ach'nar",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 6,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 6,
            "Name": "Bithoff Jonansaan",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 7,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 7,
            "Name": "H'ssani C''talan",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 8,
            "Name": "Kerran Halcyon",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 9,
            "Name": "Reena Bel Noir",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 10,
            "Name": "Talia Ska",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 3,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 11,
            "Name": "Wennic Ber'ni'lok",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 12,
            "Name": "Rhaan",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 8,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 13,
            "Name": "Durnoth",
            "Password": "mle0924j",
            "Sense": 50,
            "Control": 50,
            "Alter": 50,
            "CareerNumber": 1,
            "TraditionNumber": 9,
            "SecondNumber": 0,
            "SkillPoints": 0,
            "Quest1": 0
        },
        {
            "ID": 15,
            "Name": "Amish",
            "Password": "mle0924j",
            "Sense": 18,
            "Control": 13,
            "Alter": 13,
            "CareerNumber": 6,
            "TraditionNumber": 8,
            "SecondNumber": 7,
            "SkillPoints": 0,
            "Quest1": 1
        },
        {
            "ID": 22,
            "Name": "katrina",
            "Password": "bondage",
            "Sense": 1,
            "Control": 1,
            "Alter": 1,
            "CareerNumber": 1,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": 3,
            "Quest1": 0
        },
        {
            "ID": 23,
            "Name": "cordelia",
            "Password": "blahblah",
            "Sense": 13,
            "Control": 13,
            "Alter": 9,
            "CareerNumber": 11,
            "TraditionNumber": 1,
            "SecondNumber": 0,
            "SkillPoints": -5,
            "Quest1": 0
        }
    ];
